language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
script:
  - cd spec
  - make clean all
  - cd ../api
  - mvn clean install -B -V
