language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-recommended
      - texlive-latex-extra
      - texlive-fonts-recommended
script:
  - cd spec
  - make clean all
  - cd ../api
  - mvn clean install -B -V
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
